=== WuSangui571/mybatis/00-xml/src/main/resources/user.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--定义user标签为根标签，该标签下可以有1-n个user标签-->
<!ELEMENT users (user+)>
<!--user标签下必须有三个制定了顺序的子标签-->
<!ELEMENT user (id,name,password )>

<!--id name password 这三个标签的类型都是字符串-->
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!--
    user标签必须包含 id 选项，属性类型是 ID，约束条件是#REQUIRED
    user标签必须包含 country 选项，属性类型是 CDATA，约束条件是#IMPLIED
    user标签必须包含 plantform 选项，属性类型是 CDATA，约束条件是#FIXED
    user标签必须包含 source 选项，属性类型是 枚举，默认值是Android
-->
<!ATTLIST user
        id ID #REQUIRED
        country CDATA #IMPLIED
        plantform CDATA #FIXED "ittimeline"
        source (Android|iOS|PC|WeChat) "Android"
>

=== WuSangui571/mybatis/00-dom4j/src/main/resources/user.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "user.dtd">
<!--
定义根标签是Users
-->
<users>
    <user id = "U10001" country = "China" source = "Android">
        <id>10001</id>
        <name>sangui</name>
        <password>333</password>
        <salary>salary > 1000 &amp; salary &lt; 3000</salary>
    </user>
    <user id = "U10002" country = "US" source = "iOS">
        <id>10002</id>
        <name>Jack</name>
        <password>abc</password>
        <salary>
            <![CDATA[
            salary > 1000 & salary < 3000
            ]]>
        </salary>
    </user>
</users>
